name: Deploy to VPS

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Ustawienie klucza SSH
      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # 3. Testowanie połączenia SSH
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo SSH Connection Successful"

      # 4. Wdrożenie kodu na VPS
      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd /var/www/${{ secrets.DOMAIN_NAME }}
            git pull origin trunk
            npm install --production
            pm2 restart all
          EOF
