name: Deploy to VPS

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo SSH Connection Successful"
      
      - name: Deploy to VPS
        run: |
          ssh -T -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            if [ ! -d "/var/www/${{ secrets.DOMAIN_NAME }}/.git" ]; then
              echo "Initializing repository..."
              rm -rf /var/www/${{ secrets.DOMAIN_NAME }}
              git clone git@github.com:YOUR_USERNAME/YOUR_REPO.git /var/www/${{ secrets.DOMAIN_NAME }}
            else
              echo "Repository exists. Pulling latest changes..."
              cd /var/www/${{ secrets.DOMAIN_NAME }}
              git pull origin trunk
            fi
            npm install --production
            pm2 restart all || pm2 start npm --name "app" -- run start
          EOF
    
